# Generated by Django 5.2.15 on 2026-07-06 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('document', 'Document'), ('courrier', 'Courrier'), ('workflow', 'Workflow'), ('system', 'Système'), ('user', 'Utilisateur')], max_length=30)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône Tabler", max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
