# Generated by Django 5.2.15 on 2026-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='AgrOdiv GED', max_length=100)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#F59E0B', max_length=7)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('timezone', models.CharField(default='Africa/Algiers', max_length=50)),
                ('storage_limit', models.BigIntegerField(default=10737418240)),
                ('max_upload_size', models.IntegerField(default=52428800)),
                ('ocr_default_language', models.CharField(default='fra', max_length=10)),
                ('retention_policy', models.IntegerField(default=365)),
                ('auto_backup', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètre de l'Application",
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('size', models.BigIntegerField()),
                ('type', models.CharField(choices=[('full', 'Complet'), ('incremental', 'Incrémental'), ('manual', 'Manuel')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
