# Generated by Django 5.2.16 on 2026-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY')], default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre')], default='clair', max_length=10),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=5),
        ),
    ]
