# Generated by Django 5.2.15 on 2026-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('download', 'Download'), ('share', 'Share'), ('archive', 'Archive'), ('validate', 'Validate'), ('reject', 'Reject')], max_length=50)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('courrier', 'Courrier'), ('workflow', 'Workflow'), ('user', 'Utilisateur'), ('dossier', 'Dossier'), ('settings', 'Paramètres')], max_length=50)),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
