# Generated by Django 5.2.15 on 2026-07-06 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('organization', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='default_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.departement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.direction'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_dossiers', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.service'),
        ),
        migrations.AddField(
            model_name='dossierpermission',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='dossierpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dossierpermission',
            unique_together={('dossier', 'user')},
        ),
    ]
