# Generated by Django 5.2.15 on 2026-07-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_corbeille'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dossier',
            new_name='dossiers_do_is_dele_9710ad_idx',
            old_name='dossiers_dossier_is_deleted_idx',
        ),
    ]
