# Generated by Django 5.2.16 on 2026-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_rename_dossiers_dossier_is_deleted_idx_dossiers_do_is_dele_9710ad_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dossier_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('projet', 'Projet'), ('archive', 'Archive')], default='standard', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
    ]
