# Generated by Django 5.2.15 on 2026-07-06 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courriers', '0001_initial'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierentrant',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.departement'),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.direction'),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.service'),
        ),
        migrations.AddField(
            model_name='courrierhistorique',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='courrierhistorique',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_rediges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.departement'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.service'),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffusions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='destinataires',
            field=models.ManyToManyField(related_name='diffusions_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
