# Generated by Django 5.2.15 on 2026-07-07 21:14

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courriers', '0003_v21_updates'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courrierentrant',
            new_name='courriers_c_is_dele_cfb2c4_idx',
            old_name='courriers_entrant_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='courriersortant',
            new_name='courriers_c_is_dele_018b1f_idx',
            old_name='courriers_sortant_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='diffusion',
            new_name='courriers_d_courrie_203fdb_idx',
            old_name='courriers_diffusion_type_id_idx',
        ),
        migrations.AlterField(
            model_name='courrierhistorique',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('lecture', 'Lecture'), ('transfert', 'Transfert'), ('traitement', 'Traitement'), ('archivage', 'Archivage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diffusion',
            name='date_diffusion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='courrierentrant',
            index=models.Index(fields=['statut'], name='courriers_c_statut_7de6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='courrierentrant',
            index=models.Index(fields=['priorite'], name='courriers_c_priorit_d33742_idx'),
        ),
        migrations.AddIndex(
            model_name='courrierhistorique',
            index=models.Index(fields=['content_type', 'object_id'], name='courriers_c_content_c35376_idx'),
        ),
        migrations.AddIndex(
            model_name='courrierhistorique',
            index=models.Index(fields=['user'], name='courriers_c_user_id_a2d1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='courrierhistorique',
            index=models.Index(fields=['created_at'], name='courriers_c_created_bd70bd_idx'),
        ),
        migrations.AddIndex(
            model_name='courriersortant',
            index=models.Index(fields=['statut'], name='courriers_c_statut_31663e_idx'),
        ),
        migrations.AddIndex(
            model_name='courriersortant',
            index=models.Index(fields=['priorite'], name='courriers_c_priorit_716c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='piecejointe',
            index=models.Index(fields=['content_type', 'object_id'], name='courriers_p_content_2e176a_idx'),
        ),
    ]
