# Generated by Django 5.2.16 on 2026-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0004_rename_courriers_entrant_is_deleted_idx_courriers_c_is_dele_cfb2c4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierentrant',
            name='date_expedition',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expédition"),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='numero_enregistrement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'enregistrement"),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='numero_expedition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'expédition"),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='date_expedition',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expédition"),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='numero_expedition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'expédition"),
        ),
    ]
