# Generated by Django 5.2.16 on 2026-07-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0005_courrierentrant_date_expedition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierentrant',
            name='canal_reception',
            field=models.CharField(choices=[('email', 'Email'), ('courrier_postal', 'Courrier postal'), ('depot_physique', 'Dépôt physique')], default='courrier_postal', max_length=20, verbose_name='Canal de réception'),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='confidentialite',
            field=models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel')], default='public', max_length=20, verbose_name='Confidentialité'),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='type_courrier',
            field=models.CharField(choices=[('lettre', 'Lettre'), ('demande', 'Demande'), ('facture', 'Facture'), ('contrat', 'Contrat'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='lettre', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='canal_envoi',
            field=models.CharField(choices=[('email', 'Email'), ('courrier_postal', 'Courrier postal'), ('main_propre', 'Remise en main propre')], default='courrier_postal', max_length=20, verbose_name="Canal d'envoi"),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='confidentialite',
            field=models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel')], default='public', max_length=20, verbose_name='Confidentialité'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='signature',
            field=models.CharField(choices=[('aucune', 'Aucune'), ('electronique', 'Électronique'), ('manuscrite', 'Manuscrite')], default='aucune', max_length=20, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='type_courrier',
            field=models.CharField(choices=[('lettre', 'Lettre'), ('reponse', 'Réponse'), ('facture', 'Facture'), ('contrat', 'Contrat'), ('rapport', 'Rapport')], default='lettre', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='priorite',
            field=models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10),
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_traitement', 'En traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='courriersortant',
            name='priorite',
            field=models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10),
        ),
        migrations.AlterField(
            model_name='courriersortant',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('envoye', 'Envoyé'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
