# Generated by Django 5.2.15 on 2026-07-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0006_courrierentrant_canal_reception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, choices=[('A', 'Bâtiment A'), ('B', 'Bâtiment B'), ('C', 'Bâtiment C')], max_length=5, null=True, verbose_name='Bâtiment')),
                ('office', models.CharField(blank=True, choices=[('archives', 'Archives'), ('101', '101'), ('102', '102'), ('201', '201'), ('202', '202')], max_length=20, null=True, verbose_name='Bureau')),
                ('treasury', models.CharField(blank=True, choices=[('principale', 'Trésorerie principale'), ('secondaire', 'Trésorerie secondaire')], max_length=20, null=True, verbose_name='Trésorerie')),
                ('shelf', models.CharField(blank=True, choices=[('A', 'Étagère A'), ('B', 'Étagère B'), ('C', 'Étagère C')], max_length=5, null=True, verbose_name='Étagère')),
                ('box_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de boîte')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emplacement physique',
                'verbose_name_plural': 'Emplacements physiques',
            },
        ),
        migrations.AlterField(
            model_name='courrierentrant',
            name='canal_reception',
            field=models.CharField(choices=[('email', 'Email'), ('courrier_postal', 'Courrier postal'), ('depot_physique', 'Dépôt physique')], default='email', max_length=20, verbose_name='Canal de réception'),
        ),
        migrations.AlterField(
            model_name='courriersortant',
            name='canal_envoi',
            field=models.CharField(choices=[('email', 'Email'), ('courrier_postal', 'Courrier postal'), ('main_propre', 'Remise en main propre')], default='email', max_length=20, verbose_name="Canal d'envoi"),
        ),
        migrations.AlterField(
            model_name='courriersortant',
            name='signature',
            field=models.CharField(choices=[('aucune', 'Aucune'), ('electronique', 'Électronique'), ('manuscrite', 'Manuscrite')], default='electronique', max_length=20, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='courriersortant',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('a_envoyer', 'À envoyer'), ('envoye', 'Envoyé'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='physical_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courrier_entrant', to='courriers.physicallocation', verbose_name='Emplacement physique'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='physical_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courrier_sortant', to='courriers.physicallocation', verbose_name='Emplacement physique'),
        ),
    ]
