# Generated by Django 5.2.15 on 2026-07-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0007_add_physical_location'),
        ('organization', '0006_physicallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrierentrant',
            name='categorie',
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.categorie'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.categorie'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.direction'),
        ),
        migrations.AddField(
            model_name='physicallocation',
            name='site',
            field=models.CharField(choices=[('Siège', 'Siège'), ('Annexe', 'Annexe')], default='Siège', max_length=50, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='building',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='Bâtiment'),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='office',
            field=models.CharField(blank=True, choices=[('Archives', 'Archives'), ('101', '101'), ('102', '102'), ('201', '201'), ('202', '202')], max_length=50, null=True, verbose_name='Bureau'),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='shelf',
            field=models.CharField(blank=True, choices=[('Étagère A', 'Étagère A'), ('Étagère B', 'Étagère B'), ('C', 'Étagère C')], max_length=50, null=True, verbose_name='Étagère'),
        ),
        migrations.AlterField(
            model_name='physicallocation',
            name='treasury',
            field=models.CharField(blank=True, choices=[('Trésorerie principale', 'Trésorerie principale'), ('Trésorerie secondaire', 'Trésorerie secondaire')], max_length=50, null=True, verbose_name='Trésorerie'),
        ),
    ]
