# Generated by Django 5.2.15 on 2026-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0008_remove_courrierentrant_categorie_and_more'),
        ('organization', '0007_tag_description_tag_slug_tag_status_tag_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierentrant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organization.tag'),
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='organization.tag'),
        ),
    ]
