# Generated by Django 5.2.16 on 2026-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('valider', 'Valider'), ('refuser', 'Refuser'), ('retourner', 'Retourner')], max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('simple', 'Validation simple'), ('hierarchique', 'Validation hiérarchique')], default='simple', max_length=30, verbose_name='Type de workflow'),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
