# Generated by Django 5.2.15 on 2026-07-06 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direction',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='organization.direction'),
        ),
        migrations.AddField(
            model_name='etagere',
            name='armoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etageres', to='organization.armoire'),
        ),
        migrations.AddField(
            model_name='boitearchive',
            name='etagere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boites', to='organization.etagere'),
        ),
        migrations.AddField(
            model_name='service',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organization.departement'),
        ),
        migrations.AddField(
            model_name='service',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batiment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='organization.site'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
