# Generated by Django 5.2.16 on 2026-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='type',
            field=models.CharField(choices=[('administration', 'Administration'), ('entreprise', 'Entreprise'), ('fournisseur', 'Fournisseur'), ('client', 'Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('bleu', 'Bleu'), ('vert', 'Vert'), ('orange', 'Orange'), ('rouge', 'Rouge'), ('violet', 'Violet')], default='bleu', max_length=20),
        ),
    ]
