# Generated by Django 5.2.15 on 2026-07-20 01:49

from django.db import migrations

def seed_data(apps, schema_editor):
    Direction = apps.get_model('organization', 'Direction')
    Departement = apps.get_model('organization', 'Departement')
    Service = apps.get_model('organization', 'Service')
    Categorie = apps.get_model('organization', 'Categorie')
    Site = apps.get_model('organization', 'Site')
    Batiment = apps.get_model('organization', 'Batiment')
    Bureau = apps.get_model('organization', 'Bureau')

    if Direction.objects.exists() or Categorie.objects.exists():
        return # Skip if already seeded

    # Categories
    categories = ['Administratif', 'RH', 'Finance', 'Juridique', 'Technique', 'Contrat', 'Facture', 'Rapport', 'Autre']
    for cat in categories:
        Categorie.objects.get_or_create(name=cat, defaults={'code': cat[:3].upper()})

    # Organizations
    org_data = {
        'Direction Générale': {
            'Secrétariat Général': [],
            'Planification': []
        },
        'Direction RH': {
            'Administration RH': ['Gestion du personnel', 'Paie'],
            'Recrutement': ['Recrutement', 'Intégration'],
            'Formation': []
        },
        'Direction Financière': {
            'Comptabilité': ['Générale', 'Clients', 'Fournisseurs'],
            'Trésorerie': []
        },
        'Direction Informatique': {
            'Développement': ['Web', 'Mobile', 'API'],
            'Infrastructure': ['Réseau', 'Systèmes'],
            'Support': ['Help Desk']
        },
        'Direction Juridique': {
            'Affaires Juridiques': ['Contrats', 'Contentieux']
        },
        'Direction Commerciale': {
            'Ventes': ['B2B', 'B2C'],
            'Marketing': ['Communication', 'Digital']
        }
    }

    dir_idx = 1
    dept_idx = 1
    svc_idx = 1

    for d_name, depts in org_data.items():
        base_dir_code = d_name.replace('Direction ', 'D')[:3].upper()
        d_code = base_dir_code
        while Direction.objects.filter(code=d_code).exists():
            d_code = f"D{dir_idx:02d}"
            dir_idx += 1
        dir_obj, _ = Direction.objects.get_or_create(name=d_name, defaults={'code': d_code})
        
        for dept_name, svcs in depts.items():
            base_dept_code = dept_name[:3].upper()
            dept_code = base_dept_code
            while Departement.objects.filter(code=dept_code).exists():
                dept_code = f"DEP{dept_idx:02d}"
                dept_idx += 1
            dept_obj, _ = Departement.objects.get_or_create(name=dept_name, defaults={'direction': dir_obj, 'code': dept_code})
            
            for svc_name in svcs:
                base_svc_code = svc_name[:3].upper()
                svc_code = base_svc_code
                while Service.objects.filter(code=svc_code).exists():
                    svc_code = f"SRV{svc_idx:02d}"
                    svc_idx += 1
                Service.objects.get_or_create(name=svc_name, defaults={'departement': dept_obj, 'code': svc_code})

    # Physical Locations
    site_siege, _ = Site.objects.get_or_create(name="Siège")
    site_annexe, _ = Site.objects.get_or_create(name="Annexe")

    for b in ['A', 'B', 'C']:
        Batiment.objects.get_or_create(name=b, site=site_siege)
    
    for of_name in ['Archives', '101', '102', '201', '202']:
        Bureau.objects.get_or_create(name=of_name, batiment=Batiment.objects.filter(site=site_siege).first())

def reverse_seed_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_categorie_options_alter_departement_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
