# Generated by Django 5.2.15 on 2026-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_seed_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='Siège', max_length=200)),
                ('building', models.CharField(default='A', max_length=200)),
                ('office', models.CharField(default='Archives', max_length=200)),
                ('treasury', models.CharField(default='Trésorerie principale', max_length=200)),
                ('shelf', models.CharField(default='Étagère A', max_length=200)),
                ('box_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('document_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
