# Generated by Django 5.2.16 on 2026-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_confidentialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
