# Generated by Django 5.2.16 on 2026-07-15 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0006_courrierentrant_canal_reception_and_more'),
        ('documents', '0005_alter_document_priority_alter_document_status'),
        ('dossiers', '0005_dossier_dossier_type_dossier_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='courrier_entrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courriers.courrierentrant'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='courrier_sortant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courriers.courriersortant'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='dossiers.dossier'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='documents.document'),
        ),
    ]
