# Generated by Django 5.2.16 on 2026-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('brouillon', 'Brouillon'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
