# Generated by Django 5.2.15 on 2026-07-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0007_add_physical_location'),
        ('documents', '0007_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='physical_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='courriers.physicallocation', verbose_name='Emplacement physique'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('brouillon', 'Brouillon'), ('archive', 'Archivé')], default='actif', max_length=20),
        ),
    ]
