# Generated by Django 5.2.15 on 2026-07-20 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_physical_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(default='Unknown Scanner', max_length=255)),
                ('dpi', models.IntegerField(default=300)),
                ('color_mode', models.CharField(max_length=50)),
                ('paper_size', models.CharField(max_length=50)),
                ('duplex', models.BooleanField(default=False)),
                ('format', models.CharField(default='PDF', max_length=50)),
                ('scan_status', models.CharField(default='completed', max_length=50)),
                ('ocr_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_job', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.FileField(upload_to='scans/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_pages', to='documents.document')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.scanjob')),
            ],
        ),
    ]
