# Generated by Django 5.2.15 on 2026-07-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_ocrresult_scanjob_scannedpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='dossier',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='courrier_entrant',
            new_name='incoming_mail',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='courrier_sortant',
            new_name='outgoing_mail',
        ),
    ]
